schema_version: 1

context:
  name: module-qc-data-tools
  version: "1.2.0"
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/module_qc_data_tools-${{ version }}.tar.gz
  sha256: 66a98b38302d05ee7b46deea7569a7df5435019b657cec5143c2b9d309664990

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - module-qc-data-tools = module_qc_data_tools.cli:app
      - mqdt = module_qc_data_tools.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - numpy
    - tabulate
    - jsonschema
    - rich
    - pymongo
    - click <8.2.0
    - typer >=0.9.0
    - typing_extensions
    - itksn >=0.4.2

tests:
  - python:
      imports:
        - module_qc_data_tools
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - mqdt --help
      - mqdt --version
      - module-qc-data-tools --help
      - module-qc-data-tools --version

about:
  summary: Module qc data tools
  homepage: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-data-tools
  repository: https://gitlab.cern.ch/atlas-itk/pixel/module/module-qc-data-tools
  documentation: https://atlas-itk-pixel-mqdt.docs.cern.ch/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
    - elisabettapianori
    - marijamarjanovic
    - lime86
